apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: account-auth-policy
  namespace: account
spec:
  selector:
    matchLabels:
      app: account
  action: ALLOW
  rules:
    - from:
      - source:
          namespaces: ["istio-system"]
          principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
      - source:
          namespaces: ["post"]
          principals: ["cluster.local/ns/post/sa/post"]
      - source:
          namespaces: ["group"]
          principals: ["cluster.local/ns/group/sa/group"]
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: account-sidecar
  namespace: account
spec:
  workloadSelector:
    labels:
      app: account
  egress:
    - hosts:
      - "istio-system/*"
      - "post/post-service.post.svc.cluster.local"
      - "group/group-service.group.svc.cluster.local"
