apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-analyzer
  namespace: media-analyzer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-analyzer-deployment
  namespace: media-analyzer
  labels:
    app: media-analyzer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-analyzer
      version: v1
  template:
    metadata:
      labels:
        app: media-analyzer
        version: v1
    spec:
      serviceAccountName: media-analyzer
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
        - name: curl
          image: curlimages/curl:latest
          command: ["sh", "-c", "sleep infinity"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: media-analyzer-service
  namespace: media-analyzer
  labels:
    app: media-analyzer
spec:
  selector:
    app: media-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
