apiVersion: v1
kind: ServiceAccount
metadata:
  name: group
  namespace: group
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-deployment
  namespace: group
  labels:
    app: group
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group
      version: v1
  template:
    metadata:
      labels:
        app: group
        version: v1
    spec:
      serviceAccountName: group
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
        - name: curl # faking the account app with curl for blueprints
          image: curlimages/curl:latest
          command: ["sh", "-c", "sleep infinity"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: group
  labels:
    app: group
spec:
  selector:
    app: group
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
