apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-processor
  namespace: media-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-processor-deployment
  namespace: media-processor
  labels:
    app: media-processor
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-processor
      version: v1
  template:
    metadata:
      labels:
        app: media-processor
        version: v1
    spec:
      serviceAccountName: media-processor
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
        - name: curl # faking the account app with curl for blueprints
          image: curlimages/curl:latest
          command: ["sh", "-c", "sleep infinity"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: media-processor-service
  namespace: media-processor
  labels:
    app: media-processor
spec:
  selector:
    app: media-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
