apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: media-processor-dr
  namespace: media-processor
spec:
  host: media-processor-service.media-processor.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 5m
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: media-processor-vs
  namespace: media-processor
spec:
  hosts:
    - 'media-processor-service.media-processor.svc.cluster.local'
  http:
    - route:
        - destination:
            host: media-processor-service.media-processor.svc.cluster.local
            subset: v1
            port:
              number: 80