apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: post-dr
  namespace: post
spec:
  host: post-service.post.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 5m
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: post-vs
  namespace: post
spec:
  hosts:
    - 'post-service.post.svc.cluster.local'
  gateways:
    - istio-system/fffoto-gateway
  http:
    - route:
        - destination:
            host: post-service.post.svc.cluster.local
            subset: v1
            port:
              number: 80