name: Sync Blog Posts to MongoDB

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'blog/**/*.md'

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
        # npm ci is faster but requires package-lock.json
        # falls back to npm install if no lock file exists
      
      - name: Sync posts to MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node .github/scripts/sync-posts.js
      
      - name: Report status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Blog sync completed successfully"
          else
            echo "Blog sync failed"
          fi